routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    abort,
    send_from_directory
)
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user

import json

import redis

cache = redis.StrictRedis()

from utils import log

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u, result = User.register(form)
    print('result', result)
    return render_template("index.html", result=result)


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))


def created_topic(user_id):
    # O(n)
    # ts = Topic.all(user_id=user_id)
    # return ts

    k = 'created_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v)
        return ts
    else:
        ts = Topic.all(user_id=user_id)
        v = json.dumps([t.json() for t in ts])
        cache.set(k, v)
        return ts


def replied_topic(user_id):
    # O(k)+O(m*n)
    # rs = Reply.all(user_id=user_id)
    # ts = []
    # for r in rs:
    #     t = Topic.one(id=r.topic_id)
    #     ts.append(t)
    # return ts
    #
    k = 'replied_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v)
        return ts
    else:
        rs = Reply.all(user_id=user_id)
        ts = []
        for r in rs:
            t = Topic.one(id=r.topic_id)
            ts.append(t)

        v = json.dumps([t.json() for t in ts])
        cache.set(k, v)

        return ts


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.setting'))


@main.route('/images/<filename>')
def image(filename):
    return send_from_directory('images', filename)


@main.route('/user/<username>')
def user_detail(username):
    u = User.one(username=username)
    if u is None:
        abort(404)
    else:
        # 获取对应user的创建主题和回复主题
        creat_topics = order(Topic.all(user_id=u.id))
        reply_topics = get_reply_topics(u.id)
        return render_template('profile.html', user=u, creat_topics=creat_topics, reply_topics=reply_topics)


# 给主题按照创建日期排序，倒序
def order(ms):
    ms = sorted(ms, key=lambda m: m.created_time, reverse=True)
    return ms


# 获取回复对应的主题
def get_reply_topics(uid):
    reply_topics = []
    tids = []
    replies = order(Reply.all(user_id=uid))
    for r in replies:
        if r.topic_id not in tids:
            reply_topics.append(Topic.one(id=r.topic_id))
            tids.append(r.topic_id)
    return reply_topics


# 设置页面
@main.route('/setting')
def setting():
    u = current_user()
    return render_template('/setting.html', user=u)


# 修改用户名和签名
@main.route("/update", methods=['POST'])
def update():
    form = request.form.to_dict()
    u = current_user()
    User.update(u.id, username=form['name'])
    User.update(u.id, signature=form['signature'])
    return render_template('/setting.html', user=u)


# 修改用户密码，需要加盐
@main.route("/change_pass", methods=['POST'])
def change_pass():
    form = request.form.to_dict()
    u = current_user()
    if u.password == User.salted_password(form['old_pass']):
        User.update(u.id, password=User.salted_password(form['new_pass']))
    return render_template('/setting.html', user=u)

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()

    # 添加论坛主页用户信息
    u = current_user()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=u)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    u = current_user()
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, user=u)


@main.route("/delete")
@csrf_required
def delete():
    id = int(request.args.get('id'))
    topic = Topic.one(id=id)
    uid = topic.user_id
    u = current_user()
    if uid == u.id:
        print('删除 topic 用户是', u, id)
        Topic.delete(id)
    else:
        print('不是话题作者，无权删除')
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id', -1))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QiaoThink 个人论坛</title>
    <link rel="icon" href="/static/img/Q.png" />
    <link rel="bookmark" href="/static/img/Q.png" />
    <link rel="stylesheet" href="/static/css/index-min.css">
    <link rel="stylesheet" href="/static/css/style-index.css">
</head>
<body>
    <h2>QiaoThink 个人论坛</h2>
    <div class="container" id="container">
        <div class="form-container sign-up-container">
            <form method="post" action="{{ url_for('.register') }}">
                <h1>注册</h1>
                <input type="text" name="username" placeholder="名称">
                <input type="password" name="password" placeholder="密码">
                <button>注册</button>
            </form>
        </div>
        <div class="form-container sign-in-container">
            <form method="post" action="{{ url_for('.login') }}">
                <h1>登录</h1>
                <input type="text" name="username" placeholder="用户名">
                <input type="password" name="password" placeholder="密码">
                <button>登录</button>
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>欢迎访问！</h1>
                    <p>请您先登录。</p>
                    <button class="ghost" id="signIn">登录</button>
                </div>
                <div class="overlay-panel overlay-right">
                    {% if result %}
                        <p>{{ result }}</p>
                    {% else %}
                        <h1>你好朋友！</h1>
                        <p>输入您的个人信息注册成为会员。</p>
                        <p>您也可以使用测试账号。</p>
                        <p>测试账号：abc &nbsp;&nbsp;密码：123</p>
                    {% endif %}
                    <button class="ghost" id="signUp">注册</button>
                </div>
            </div>
        </div>
    </div>
    <script src="/static/js/index.js"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QiaoThink 个人论坛</title>
    <link rel="icon" href="/static/img/Q.png" />
    <link rel="bookmark" href="/static/img/Q.png" />
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
{% extends "topic/base.html" %}
{% block title %}近期动态{% endblock%}
{% block a %}<a href="{{ url_for('index.user_detail', username = user.username) }}">动态</a>{% endblock %}
{% block main %}

<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <img src="{{ user.image }}" width="100px" height="100px">
                        <span class="user_name">
                            <a class="dark" href="{{ url_for('index.user_detail', username = user.username) }}">
                                {{ user.username }}
                            </a>
                        </span>
                        <div class="space clearfix"></div>
                        <span class="signature">
                        " {{ user.signature }} "
                        </span>
                    </div>
                </div>

            </div>

        </div>

        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('topic.new') }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>

    </div>

    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('topic.index') }}">主页</a><span class="divider">/</span></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src="{{ user.image }}">
                </div>
                <a class="dark">{{ user.username }}</a>
                <p class="col_fade">注册时间：{{ user.created_time | format_time }}</p>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>
            <div class="inner">
                <div class="topic_list">
                {% for t in creat_topics %}
                    <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="user_avatar" href="{{ url_for('topic.index') }}">
                            <img src="{{ user.image }}">
                        </a>
                        <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                            {{ t.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                            {{ t.views }}
                        </span>
                        </span>
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                                创建时间：{{ t.created_time | format_time }}
                            </a>
                        {% set r = t.last_reply() %}
                            {%  if r == None %}
                                <a class='dark reply_author'>
                                    最新回复：{{ r }}
                                </a>
                            {% else %}
                                <span class='cell reply_area reply_item'>
                                    <a class='dark reply_author'>
                                        最新回复：{{ r.user().username }}
                                    </a>
                                    <a class="reply_time">
                                        <span class="emean-time" data-created_time="{{ r.created_time }}"></span>
                                    </a>
                                </span>
                            {% endif %}
                    </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="header">
            <span class="col_fade">最近参与的话题</span>
            </div>

            <div class="inner">
            {% for t in reply_topics %}
                <div class="cell">
                    <div class="topic_title_wrapper">
                        <a class="user_avatar" href="{{ url_for('topic.index') }}">
                            <img src="{{ user.image }}">
                        </a>
                        <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                            {{ t.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                            {{ t.views }}
                        </span>
                        </span>
                        <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                            {{ t.title }}
                        </a>
                        {% set r = t.last_reply() %}
                            {%  if r == None %}
                                <a class='dark reply_author'>
                                    最新回复：{{ r }}
                                </a>
                            {% else %}
                                <span class='cell reply_area reply_item'>
                                    <a class='dark reply_author'>
                                        最新回复：{{ r.user().username }}
                                        回复时间：{{ r.created_time | format_time }}
                                    </a>
                                    <a class="reply_time">
                                        <span class="emean-time" data-created_time="{{ r.created_time }}"></span>
                                    </a>
                                </span>
                            {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>

        </div>

    </div>

</div>
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>

<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function () {
        // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var registerTimer = function () {
        setInterval(function () {
            var times = es('.emean-time')
            for (var i = 0; i < times.length; i++) {
                var t = times[i]
                var time = Number(t.dataset.created_time)
                var now = Math.floor(new Date() / 1000)
                var delta_s = now - time
                var delta_m = Math.floor((now - time) / 60)
                var delta_h = Math.floor((now - time) / 3600)
                var delta_d = Math.floor((now - time) / 3600 / 24)
                var s = `${delta_d} 天前， ${delta_h} 小时前， ${delta_m} 分钟前， ${delta_s} 秒前`
                t.innerText = s
            }
        }, 1000)
    }

    var __main = function () {
        markContents()
        highlight()
        registerTimer()
    }

    __main()

</script>
{% endblock %}

templates/setting.html
{% extends "topic/base.html" %}
{% block title %}个人设置{% endblock%}
{% block a %}<a href="{{ url_for('index.user_detail', username = user.username) }}">动态</a>{% endblock %}
{% block main %}
<!-- navbar -->
<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <img src="{{ user.image }}">
                        <span class="user_name">
                            <a class="dark" href="{{ url_for('index.user_detail', username = user.username) }}">
                                {{ user.username }}
                            </a>
                        </span>
                        <div class="space clearfix"></div>
                        <span class="signature">
                        {{ user.signature }}
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel">
            <div class="inner">
                <a href="/topic/new" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>

<div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href={{ url_for('topic.index') }} marked="1">主页</a><span class="divider">/</span></li>
        <li class="active">设置</li>
      </ul>
    </div>
    <div class="inner">
      <form id="setting_form" class="form-horizontal" action="{{ url_for('index.update')}}" method="post">
        <div class="control-group">
          <label class="control-label" for="name">用户名</label>

          <div class="controls">
            <input class="input-xlarge readonly" id="name" name="name" size="30" type="text" value={{ user.username }}>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="signature">个性签名</label>

          <div class="controls">
            <textarea class="input-xlarge" id="signature" name="signature" size="30"></textarea>
          </div>
        </div>
        <input type="hidden" id="action" name="action" value="change_setting">
        <div class="form-actions">
          <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
        </div>
      </form>
    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">更改密码</span>
    </div>
    <div class="inner">
      <form id="change_pass_form" class="form-horizontal" action="{{ url_for('index.change_pass')}}" method="post">
        <div class="control-group">
          <label class="control-label" for="old_pass">当前密码</label>

          <div class="controls">
            <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="new_pass">新密码</label>

          <div class="controls">
            <input class="input-xlarge" type="password" id="new_pass" name="new_pass" size="30">
          </div>
        </div>
        <input type="hidden" id="action" name="action" value="change_password">

        <div class="form-actions">
          <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
        </div>
      </form>
    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">上传头像</span>
    </div>
    <div class="inner">
        <img src="{{ user.image }}">
        <form method="post"
            action="{{ url_for('.avatar_add')}}"
            enctype="multipart/form-data"
            >
            <input type="file" name="avatar">
            <button type="submit">上传头像</button>
        </form>
    </div>
  </div>
</div>

</div>

<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>

{% endblock %}